# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 171f4d4b43367274fee3ce26c2fcc93a6f406a5d89dd4a86f87475923e92d242404fc5e3438ac57a07f73723c3b6d9ef80e42206dbb0b05aaaaa5846d6e8508e

test:
  secret_key_base: 3a992e13442ff4ef27ce92c9bceeb7c7dee090a1fcff1a1cd9eecf7f489809c11b961d9001d04135dbc9d1f60f33c5106f5b21dac14590955805e852f2269a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
